spring:
  datasource:
    url: jdbc:h2:file:C:/Users/lucas/IdeaProjects/trazar/trazardb
    username: sa
    password: qwerty

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true



